os: linux
language: node_js
node_js: 12
python: "2.7"
# branches:
#     only:
#         - master
install:
    - yarn
script:
    - npm run lint
    - npm run electron:build
cache:
    directories:
        - node_modules
