os: linux
language: node_js
node_js:
    - 10
    - 12
    - 14
    - node
python: "2.7"
install:
    - yarn
script:
    - npm run lint
    - npm run electron:build
cache:
    directories:
        - node_modules
