name: Merge branch with dependencies
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "14"
      - run: yarn
      - run: npm run lint
      - run: npm run electron:build
      - name: Merge by dependencies
        uses: devmasx/merge-branch@v1.3.1
        with:
          label_name: "dependencies"
          target_branch: "master"
          github_token: ${{ github.token }}
